image: ubuntu

install:
  # Install dbus-python dependencies
  - sudo apt update
  - sudo apt install -y libdbus-1-dev libdbus-glib-1-dev

  # Install PyGObject dependencies
  - sudo apt install -y libcairo2-dev libgirepository1.0-dev

  # Install PyGObject dependencies required for building
  - sudo apt install -y gir1.2-gtk-3.0 gir1.2-appindicator3-0.1

  # Install pip stuff needed to run tests
  - sudo apt install -y python3-pip
  - pip3 install -U setuptools

  # codecov stuff
  - sudo pip3 install codecov

  # Install project requirements
  - pip3 install -r requirements.txt

  # Inject Twitch Client ID into config
  - sed -i 's@p0gch4mp101fy451do9uod1s1x9i4a@'"$TWITCH_API_CLIENT_ID"'@' config.yaml.example
  - sed -i 's@itqb0thqi5cek18ae6ekm7pbqvh63k@'"$TWITCH_API_CLIENT_SECRET"'@' config.yaml.example

  # Set up config files for running from source and with PyPI install
  - cp config.yaml.example config.yaml
  - mkdir -p $HOME/.config/twitch-game-notify
  - cp config.yaml $HOME/.config/twitch-game-notify/config.yaml

build: off

test_script:
  # Test
  - coverage run ./setup.py test
  - coverage run run_twitchgamenotify.py --print-config
  - coverage run run_twitchgamenotify.py --one-shot --print-to-terminal
  - coverage run run_twitchgamenotify.py --one-shot --print-to-terminal --loglevel info

after_test:
  # Upload coverage data to CodeCov
  - codecov
