image: ubuntu

install:
  # Install pip requirements and D-Bus dependencies
  - sudo apt install -y python3-pip libdbus-1-dev libdbus-glib-1-dev
  - pip3 install -r requirements.txt

  # Code cov
  - pip3 install codecov

build: off

test_script:
  # Test not being able to find a config file
  - coverage run --source='.' run_twitchgamenotify.py --print-to-terminal

  # Test normally
  - cp config.yaml.example config.yaml
  - coverage run --source='.' run_twitchgamenotify.py --print-to-terminal

after_test:
  # Upload coverage data to CodeCov
  - codecov
